### ISSUE TITLE
Requesting digitalOcean support

### ISSUE THREAD

**Issue by kadjangujoseph** [kilamaelie/build-and-deploy-reactApp-to-aws-ec2-via-github-actions#18]
Hello Elie,

hope you are doing good, this is a nice work you have done. I would like to know if you could do the same for the DigitalOcean droplet for us, user of DigitalOcean.

Thank you.

**Comment by kilamaelie** [comment]
Hey Joseph,

hank you for your positive feedback! I'm delighted to hear that you found the work useful. I'm currently working on a tutorial specifically focused on DigitalOcean droplets, and I'll be sure to cover the aspects you're interested in. Stay tuned for the next tutorial, I'll keep you posted on its progress. If you have any specific requests or preferences for the tutorial, please let me know. I look forward to sharing the DigitalOcean droplet guide with you!
